# ====== global_costmap_params.yaml ======
global_costmap:
  global_frame: map
  
  # --- Режим "Большой Радар" ---
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 40.0
  height: 40.0
  resolution: 0.05
  inflation_radius: 1.2
  
  # --- Плагины ---
  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    - {name: grass_layer,     type: "costmap_2d::ObstacleLayer"}  # Трава (облако точек)
    - {name: road_layer,      type: "costmap_2d::StaticLayer"}    # Дорога (сетка)
    - {name: road_inflation,  type: "costmap_2d::InflationLayer"}  # Раздутие дороги/травы (слабое)

  # --- Настройки плагинов ---
  static_layer:
    enabled: true
    # Этот слой будет "подхватывать" карту от SLAM, но не будет управлять размером costmap
    map_topic: /map 
    
  # obstacle_layer теперь в costmap_common.yaml, 
  # но для глобальной карты мы УБИРАЕМ траву, оставляем только лазер
  obstacle_layer:
    observation_sources: laser_scan_sensor
    
  inflation_layer:
    enabled: true
    inflation_radius: 1.2
    cost_scaling_factor: 6.5


  road_inflation:
    enabled: true
    inflation_radius: 0.4    # Маленький отступ от края дороги
    cost_scaling_factor: 10.0


  # road_layer настройки будут подхвачены из costmap_common.yaml
  # но мы можем добавить специфичные лимиты здесь если нужно

  # # --- Настройки для СЛОЯ ДОРОГИ (path_detector) ---
  # path_layer:
  #   enabled: true
  #   map_topic: path_detector/costmap
  #   subscribe_to_updates: true