local_costmap:
  # --- Общие параметры карты ---
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 6.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05
  transform_tolerance: 0.8

  # --- Список Плагинов ---
  # InflationLayer раздувает только то, что было добавлено ПРЕДЫДУЩИМИ слоями.
  # Поэтому мы ставим инфляцию лазера выше, чем инфляцию дороги.
  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}  # Лазер
    - {name: laser_inflation, type: "costmap_2d::InflationLayer"} # Раздутие лазера (сильное)
    - {name: grass_layer,     type: "costmap_2d::ObstacleLayer"}  # Трава (облако точек)
    - {name: road_layer,      type: "costmap_2d::DetectedPathLayer"}    # Дорога (custom plugin)
    - {name: road_inflation,  type: "costmap_2d::InflationLayer"}  # Раздутие дороги/травы (слабое)
  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {
      data_type: LaserScan,
      topic: /scan_filtered, 
      sensor_frame: sensor_laser_link,
      marking: true,
      clearing: false,
      observation_persistence: 0.1, 
      footprint_clearing_enabled: true 
    }
  obstacle_range: 3.5
  raytrace_range: 4.2
  # --- Настройки инфляции для ЛАЗЕРА ---
  laser_inflation:
    enabled: true
    inflation_radius: 0.8    # Большой отступ от стен
    cost_scaling_factor: 3.0

  # --- Настройки инфляции для ДОРОГИ ---
  road_inflation:
    enabled: true
    inflation_radius: 0.25    # Маленький отступ от края дороги
    cost_scaling_factor: 5.5

  # Настройки слоев подхватываются из costmap_common.yaml по именам
