local_costmap:
  # --- Общие параметры карты ---
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 6.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.1
  transform_tolerance: 0.8

  # --- Список Плагинов ---
  # InflationLayer раздувает только то, что было добавлено ПРЕДЫДУЩИМИ слоями.
  # Поэтому мы ставим инфляцию лазера выше, чем инфляцию дороги.
  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}  # Лазер
    - {name: laser_inflation, type: "costmap_2d::InflationLayer"} # Раздутие лазера (сильное)
    - {name: grass_layer,     type: "costmap_2d::ObstacleLayer"}  # Трава (облако точек)
    - {name: road_layer,      type: "costmap_2d::StaticLayer"}    # Дорога (сетка)
    - {name: road_inflation,  type: "costmap_2d::InflationLayer"}  # Раздутие дороги/травы (слабое)

  # --- Настройки инфляции для ЛАЗЕРА ---
  laser_inflation:
    enabled: true
    inflation_radius: 0.8    # Большой отступ от стен
    cost_scaling_factor: 3.0

  # --- Настройки инфляции для ДОРОГИ ---
  road_inflation:
    enabled: true
    inflation_radius: 0.3    # Маленький отступ от края дороги
    cost_scaling_factor: 10.0

  # Настройки слоев подхватываются из costmap_common.yaml по именам
