# Параметры для ImprovedDWALocalPlanner (на основе статьи Qin et al. 2022)

# Имя плагина, используется как пространство имен (namespace)
ImprovedDWALocalPlanner:

  # --- Весовые коэффициенты оценочной функции ---
  alpha: 0.3         # Приоритет следования глобальному плану (heading)
  beta: 15.5          # Приоритет избегания СТАТИЧЕСКИХ препятствий (dist)
  gamma: 0.4       # Приоритет поддержания высокой скорости (velocity)
  kappa: 3.5        # Приоритет "умных" маневров относительно ДИНАМИЧЕСКИХ препятствий (dis_hv)
  epsilon: 8.5       # Приоритет поддержания безопасной дистанции до ДИНАМИЧЕСКИХ препятствий (dis_fp)


  # --- Ограничения движения робота ---
  max_vel_x: 1.0     # Макс. линейная скорость, м/с
  min_vel_x: 0.0     # Мин. линейная скорость, м/с (0.0 запрещает движение назад)
  max_vel_th: 3.14    # Макс. угловая скорость, рад/с
  
  acc_lim_x: 2.0     # Макс. линейное ускорение, м/с^2 
  acc_lim_th: 2.0    # Макс. угловое ускорение, рад/с^2

  # --- Параметры симуляции траекторий ---
  predict_time: 2.5  # На сколько секунд вперед симулировать движение
  dt: 0.1            # Шаг времени для симуляции, с
  vx_samples: 20     # Количество проверяемых линейных скоростей
  vth_samples: 40    # Количество проверяемых угловых скоростей
  
  # --- Параметры достижения цели ---
  xy_goal_tolerance: 0.35   # Допустимая ошибка по расстоянию до цели, м
  yaw_goal_tolerance: 0.5  # Допустимая ошибка по углу в конечной точке, рад
  trans_stopped_vel: 0.1    # Порог скорости, ниже которого робот считается остановившимся
  rot_stopped_vel: 0.1      # Порог угловой скорости для остановки